// <auto-generated />
using System;
using MDSnkeakShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MDSnkeakShop.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240913135250_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MDSnkeakShop.Models.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("brand");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Carrello", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.Property<int>("ID_Utente")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("carrello");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.CartaCredito", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID_Utente")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCarta")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("ID");

                    b.ToTable("cartacredito");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Categoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Colore", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("colore");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.DettagliRifornimento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Colore")
                        .HasColumnType("int");

                    b.Property<int>("ID_Rifornimento")
                        .HasColumnType("int");

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.Property<int>("ID_Taglia")
                        .HasColumnType("int");

                    b.Property<int>("Qta_aggiungi_per_taglia")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("dettaglirifornimento");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.DettagliScarpa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.Property<int>("ID_Taglia")
                        .HasColumnType("int");

                    b.Property<int>("Qta_taglia")
                        .HasColumnType("int");

                    b.Property<float>("prezzo_al_dettaglio")
                        .HasColumnType("float");

                    b.Property<float>("sconto_applicabile")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("dettagliscarpa");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Magazziniere", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("magazziniere");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Modello", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("modello");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Negozio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("negozio");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Ordine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("Costo_totale")
                        .HasColumnType("float");

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.Property<int>("ID_Utente")
                        .HasColumnType("int");

                    b.Property<int>("Qta_prodotto")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ordine");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Pagamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("pagamento");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Piuvenduti", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("piuvenduti");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Rifornimento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Magazziniere")
                        .HasColumnType("int");

                    b.Property<int>("ID_Negozio")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("rifornimento");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Scarpa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Brand")
                        .HasColumnType("int");

                    b.Property<int>("ID_Categoria")
                        .HasColumnType("int");

                    b.Property<int>("ID_Colore")
                        .HasColumnType("int");

                    b.Property<int>("ID_Modello")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("scarpa");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.ScarpaColore", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Colore")
                        .HasColumnType("int");

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("scarpacolore");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.StoricoOrdine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Ordine")
                        .HasColumnType("int");

                    b.Property<int>("ID_Utente")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("storicoordine");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Taglia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("ID");

                    b.ToTable("taglia");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Whislist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.Property<int>("ID_Utente")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("whislist");
                });

            modelBuilder.Entity("Utente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Viadicasa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("utente");
                });
#pragma warning restore 612, 618
        }
    }
}
