// <auto-generated />
using System;
using MDSnkeakShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MDSnkeakShop.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MDSnkeakShop.Models.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("brand");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Carrello", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.Property<int>("ID_Utente")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Scarpa");

                    b.HasIndex("ID_Utente");

                    b.ToTable("carrello");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.CartaCredito", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID_Utente")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCarta")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("ID");

                    b.HasIndex("ID_Utente");

                    b.ToTable("cartacredito");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Categoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Colore", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("colore");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.DettagliRifornimento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Colore")
                        .HasColumnType("int");

                    b.Property<int>("ID_Rifornimento")
                        .HasColumnType("int");

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.Property<int>("ID_Taglia")
                        .HasColumnType("int");

                    b.Property<int>("Qta_aggiungi_per_taglia")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Colore");

                    b.HasIndex("ID_Rifornimento");

                    b.HasIndex("ID_Scarpa");

                    b.HasIndex("ID_Taglia");

                    b.ToTable("dettaglirifornimento");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.DettagliScarpa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.Property<int>("ID_Taglia")
                        .HasColumnType("int");

                    b.Property<int>("Qta_taglia")
                        .HasColumnType("int");

                    b.Property<float>("prezzo_al_dettaglio")
                        .HasColumnType("float");

                    b.Property<float>("sconto_applicabile")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("ID_Scarpa");

                    b.HasIndex("ID_Taglia");

                    b.ToTable("dettagliscarpa");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Magazziniere", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("magazziniere");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Modello", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("modello");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Negozio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("negozio");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Ordine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("Costo_totale")
                        .HasColumnType("float");

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.Property<int>("ID_Utente")
                        .HasColumnType("int");

                    b.Property<int>("Qta_prodotto")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Scarpa");

                    b.HasIndex("ID_Utente");

                    b.ToTable("ordine");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Pagamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("pagamento");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Piuvenduti", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Scarpa");

                    b.ToTable("piuvenduti");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Rifornimento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Magazziniere")
                        .HasColumnType("int");

                    b.Property<int>("ID_Negozio")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Magazziniere");

                    b.HasIndex("ID_Negozio");

                    b.ToTable("rifornimento");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Scarpa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Brand")
                        .HasColumnType("int");

                    b.Property<int>("ID_Categoria")
                        .HasColumnType("int");

                    b.Property<int>("ID_Colore")
                        .HasColumnType("int");

                    b.Property<int>("ID_Modello")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Brand");

                    b.HasIndex("ID_Categoria");

                    b.HasIndex("ID_Colore");

                    b.HasIndex("ID_Modello");

                    b.ToTable("scarpa");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.ScarpaColore", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Colore")
                        .HasColumnType("int");

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Colore");

                    b.HasIndex("ID_Scarpa");

                    b.ToTable("scarpacolore");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.StoricoOrdine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Ordine")
                        .HasColumnType("int");

                    b.Property<int>("ID_Utente")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Ordine");

                    b.HasIndex("ID_Utente");

                    b.ToTable("storicoordine");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Taglia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("ID");

                    b.ToTable("taglia");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Whislist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_Scarpa")
                        .HasColumnType("int");

                    b.Property<int>("ID_Utente")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ID_Scarpa");

                    b.HasIndex("ID_Utente");

                    b.ToTable("whislist");
                });

            modelBuilder.Entity("Utente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Viadicasa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("ID");

                    b.ToTable("utente");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Carrello", b =>
                {
                    b.HasOne("MDSnkeakShop.Models.Scarpa", "scarpa")
                        .WithMany()
                        .HasForeignKey("ID_Scarpa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Utente", "utente")
                        .WithMany()
                        .HasForeignKey("ID_Utente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("scarpa");

                    b.Navigation("utente");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.CartaCredito", b =>
                {
                    b.HasOne("Utente", "utente")
                        .WithMany()
                        .HasForeignKey("ID_Utente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("utente");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.DettagliRifornimento", b =>
                {
                    b.HasOne("MDSnkeakShop.Models.Colore", "colore")
                        .WithMany()
                        .HasForeignKey("ID_Colore")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MDSnkeakShop.Models.Rifornimento", "rifornimento")
                        .WithMany()
                        .HasForeignKey("ID_Rifornimento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MDSnkeakShop.Models.Scarpa", "scarpa")
                        .WithMany()
                        .HasForeignKey("ID_Scarpa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MDSnkeakShop.Models.Taglia", "taglia")
                        .WithMany()
                        .HasForeignKey("ID_Taglia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("colore");

                    b.Navigation("rifornimento");

                    b.Navigation("scarpa");

                    b.Navigation("taglia");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.DettagliScarpa", b =>
                {
                    b.HasOne("MDSnkeakShop.Models.Scarpa", "scarpa")
                        .WithMany()
                        .HasForeignKey("ID_Scarpa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MDSnkeakShop.Models.Taglia", "taglia")
                        .WithMany()
                        .HasForeignKey("ID_Taglia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("scarpa");

                    b.Navigation("taglia");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Ordine", b =>
                {
                    b.HasOne("MDSnkeakShop.Models.Scarpa", "scarpa")
                        .WithMany()
                        .HasForeignKey("ID_Scarpa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Utente", "utente")
                        .WithMany()
                        .HasForeignKey("ID_Utente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("scarpa");

                    b.Navigation("utente");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Piuvenduti", b =>
                {
                    b.HasOne("MDSnkeakShop.Models.Scarpa", "scarpa")
                        .WithMany()
                        .HasForeignKey("ID_Scarpa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("scarpa");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Rifornimento", b =>
                {
                    b.HasOne("MDSnkeakShop.Models.Magazziniere", "magazziniere")
                        .WithMany()
                        .HasForeignKey("ID_Magazziniere")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MDSnkeakShop.Models.Negozio", "negozio")
                        .WithMany()
                        .HasForeignKey("ID_Negozio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("magazziniere");

                    b.Navigation("negozio");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Scarpa", b =>
                {
                    b.HasOne("MDSnkeakShop.Models.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("ID_Brand")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MDSnkeakShop.Models.Categoria", "categoria")
                        .WithMany()
                        .HasForeignKey("ID_Categoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MDSnkeakShop.Models.Colore", "colore")
                        .WithMany()
                        .HasForeignKey("ID_Colore")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MDSnkeakShop.Models.Modello", "modello")
                        .WithMany()
                        .HasForeignKey("ID_Modello")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("brand");

                    b.Navigation("categoria");

                    b.Navigation("colore");

                    b.Navigation("modello");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.ScarpaColore", b =>
                {
                    b.HasOne("MDSnkeakShop.Models.Colore", "colore")
                        .WithMany()
                        .HasForeignKey("ID_Colore")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MDSnkeakShop.Models.Scarpa", "scarpa")
                        .WithMany()
                        .HasForeignKey("ID_Scarpa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("colore");

                    b.Navigation("scarpa");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.StoricoOrdine", b =>
                {
                    b.HasOne("MDSnkeakShop.Models.Ordine", "ordine")
                        .WithMany()
                        .HasForeignKey("ID_Ordine")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Utente", "utente")
                        .WithMany()
                        .HasForeignKey("ID_Utente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ordine");

                    b.Navigation("utente");
                });

            modelBuilder.Entity("MDSnkeakShop.Models.Whislist", b =>
                {
                    b.HasOne("MDSnkeakShop.Models.Scarpa", "scarpa")
                        .WithMany()
                        .HasForeignKey("ID_Scarpa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Utente", "utente")
                        .WithMany()
                        .HasForeignKey("ID_Utente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("scarpa");

                    b.Navigation("utente");
                });
#pragma warning restore 612, 618
        }
    }
}
